// Assembles a self-contained production payload under ./release/app:
//   release/app/
//     server/server.mjs        bundled server (own code; npm deps external)
//     server/migrations/        drizzle SQL migrations (server self-applies)
//     dist/                      built SPA
//     node_modules/             server-only production deps (incl. native better-sqlite3)
//     package.json              minimal prod manifest
//
// After this runs you still need to (1) drop a Windows node.exe into release/app,
// and (2) compile the Inno Setup installer. See INSTALL_BUILD.md.

import { build } from 'esbuild'
import { execSync } from 'node:child_process'
import { rmSync, mkdirSync, cpSync, writeFileSync, existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const releaseApp = resolve(root, 'release', 'app')

// Server-only production dependencies. Frontend deps are compiled into dist by
// Vite and are NOT needed at runtime by the server.
const PROD_DEPS = {
  'better-sqlite3': '^12.10.0',
  '@fastify/static': '^9.1.3',
  '@fastify/websocket': '^11.2.0',
  '@fastify/helmet': '^13.0.2',
  '@fastify/rate-limit': '^10.3.0',
  'drizzle-orm': '^0.45.2',
  'fastify': '^5.8.5',
  // Runtime validation of imported content packs (server-side import endpoint).
  'zod': '^3.25.76',
  // After-action report PDF generation (server/reports/sessionReportPdf.ts).
  'pdfkit': '^0.18.0',
  // LLM SDKs — the DM now runs server-side (M4).
  '@anthropic-ai/sdk': '^0.39.0',
  'openai': '^6.38.0',
  '@google/generative-ai': '^0.24.1',
  // TLS. DICE serves HTTPS by default and generates its own certificate on
  // first run (selfsigned); acme-client obtains a publicly-trusted one when a
  // host configures a domain. Both are pure JS — no native build step.
  'selfsigned': '^5.5.0',
  'acme-client': '^5.4.0',
}

const run = (cmd, cwd = root) => execSync(cmd, { cwd, stdio: 'inherit' })

console.log('\n[1/5] Clean release/app')
rmSync(resolve(root, 'release'), { recursive: true, force: true })
mkdirSync(resolve(releaseApp, 'server'), { recursive: true })

console.log('\n[2/5] Build SPA (vite build)')
run('npm run build')

console.log('\n[3/5] Bundle server (esbuild)')
await build({
  entryPoints: [resolve(root, 'server', 'index.ts')],
  bundle:   true,
  platform: 'node',
  format:   'esm',               // ESM so import.meta.url resolves correctly
  target:   'node20',
  packages: 'external',          // npm deps resolved from node_modules at runtime
  outfile:  resolve(releaseApp, 'server', 'server.mjs'),
})

console.log('\n[4/5] Copy SPA + migrations + launcher')
cpSync(resolve(root, 'dist'), resolve(releaseApp, 'dist'), { recursive: true })
cpSync(resolve(root, 'server', 'db', 'migrations'), resolve(releaseApp, 'server', 'migrations'), { recursive: true })
cpSync(resolve(root, 'installer', 'DICE.cmd'), resolve(releaseApp, 'DICE.cmd'))
cpSync(resolve(root, 'installer', 'DICE-LAN.cmd'), resolve(releaseApp, 'DICE-LAN.cmd'))
cpSync(resolve(root, 'installer', 'DICE-Internet.cmd'), resolve(releaseApp, 'DICE-Internet.cmd'))
const icoSrc = resolve(root, 'installer', 'dice.ico')
if (existsSync(icoSrc)) {
  cpSync(icoSrc, resolve(releaseApp, 'dice.ico'))
  console.log('    + bundled dice.ico (shortcut/app icon)')
} else {
  console.log('    i no installer/dice.ico found — shortcuts will use a default icon')
}

console.log('\n[5/5] Install server-only production dependencies')
writeFileSync(
  resolve(releaseApp, 'package.json'),
  JSON.stringify({ name: 'dice-runtime', private: true, version: '0.1.0', dependencies: PROD_DEPS }, null, 2),
)
run('npm install --omit=dev --legacy-peer-deps --no-audit --no-fund', releaseApp)

// Bundle the build machine's own node.exe so the runtime ABI matches the
// better-sqlite3 prebuild that was just installed. Only valid when building on
// Windows x64; otherwise drop a matching Windows node.exe in manually.
const node = resolve(releaseApp, 'node.exe')
if (process.platform === 'win32' && process.execPath.toLowerCase().endsWith('node.exe')) {
  cpSync(process.execPath, node)
  console.log(`\n[+] Bundled node.exe (${process.version}, ABI-matched to better-sqlite3)`)
}

// Single-source the installer version from package.json. The Inno Setup script
// `installer/dice.iss` does `#include "version.iss"` to pick this up, so every
// release just needs `package.json` bumped — no second place to edit.
const pkgVersion = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf-8')).version
const versionIssPath = resolve(root, 'installer', 'version.iss')
writeFileSync(
  versionIssPath,
  `; Generated by scripts/build-release.mjs from package.json — do not edit by hand.\n#define AppVersion "${pkgVersion}"\n`,
)
console.log(`\n[+] Wrote installer/version.iss with AppVersion = ${pkgVersion}`)

console.log('\n✓ Release payload assembled at release/app')
console.log(existsSync(node)
  ? '  node.exe present — ready to compile the Inno Setup installer (see INSTALL_BUILD.md).'
  : '  NEXT: place a Windows x64 node.exe in release/app (see INSTALL_BUILD.md), then compile the installer.')
